// <auto-generated />
using System;
using Abadar.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Abadar.Backend.Data.Migrations
{
    [DbContext(typeof(AbadarDbContext))]
    [Migration("20261008103527_Version2EventDriven")]
    partial class Version2EventDriven
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Abadar.Backend.Models.AnalyticsProjection", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("TotalNotional")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)")
                        .HasColumnName("total_notional");

                    b.Property<decimal>("TotalQuantity")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)")
                        .HasColumnName("total_quantity");

                    b.Property<long>("TradeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("trade_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Symbol");

                    b.ToTable("analytics_projections", (string)null);
                });

            modelBuilder.Entity("Abadar.Backend.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset?>("LastOnline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_online");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Abadar.Backend.Models.ExchangeOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Price")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)")
                        .HasColumnName("price");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("RemainingQuantity")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)")
                        .HasColumnName("remaining_quantity");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("side");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("symbol");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_symbol_sequence");

                    b.HasIndex("Symbol", "Status")
                        .HasDatabaseName("ix_orders_symbol_status");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Abadar.Backend.Models.ExchangeTrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("buy_order_id");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<decimal>("Price")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)")
                        .HasColumnName("price");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SellOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sell_order_id");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt")
                        .HasDatabaseName("ix_trades_executed_at");

                    b.HasIndex("Symbol", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_trades_symbol_sequence");

                    b.ToTable("trades", (string)null);
                });

            modelBuilder.Entity("Abadar.Backend.Models.IntegrationEventOutbox", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aggregate_type");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("partition_key");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("EventId");

                    b.HasIndex("PublishedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_unpublished");

                    b.HasIndex("Topic", "PartitionKey", "Sequence")
                        .HasDatabaseName("ix_outbox_stream_sequence");

                    b.ToTable("integration_event_outbox", (string)null);
                });

            modelBuilder.Entity("Abadar.Backend.Models.MarketProjection", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("LastPrice")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)")
                        .HasColumnName("last_price");

                    b.Property<long>("TradeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("trade_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Volume")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)")
                        .HasColumnName("volume");

                    b.HasKey("Symbol");

                    b.ToTable("market_projections", (string)null);
                });

            modelBuilder.Entity("Abadar.Backend.Models.PortfolioPosition", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Asset")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("asset");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(30, 10)
                        .HasColumnType("numeric(30,10)")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId", "Asset");

                    b.ToTable("portfolio_positions", (string)null);
                });

            modelBuilder.Entity("Abadar.Backend.Models.ProcessedIntegrationEvent", b =>
                {
                    b.Property<string>("Consumer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("consumer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Consumer", "EventId");

                    b.ToTable("processed_events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
